config/routes.rb
Facepon::Application.routes.draw do

  root 'main#welcome'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', :as => :logout

  resources :pages do
    collection do
      get 'build_pages_collection'
    end

    resources :conversations, :controller => 'page/conversations' do
      collection do
        get 'fetch_from_fb'
      end

      resources :messages, :controller => 'page/messages' do
      end
    end
  end

  

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id            :integer          not null, primary key
#  page_id       :integer
#  fbconv_id     :string(255)
#  updated_time  :datetime
#  link          :string(255)
#  message_count :integer
#  unread_count  :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Conversation < ActiveRecord::Base

  belongs_to :page
  has_many :messages

  validates_uniqueness_of :fbconv_id
  validates_presence_of :fbconv_id, :updated_time


  def duplicate?(_updated_time)
    self.updated_time == _updated_time
  end

end

app/controllers/page/conversations_controller.rb
class Page::ConversationsController < ApplicationController

  before_action :find_page

  def index
    @conversations = @page.conversations
  end

  def fetch_from_fb
    require "fb_tools"
    cp = FBTools::ConversationParser.new(@page)
    cp.fetch_and_parse_and_store

    render :js => "alert('Success!!');"
  end

  protected

    def find_page
      @page = Page.find(params[:page_id])
    end

end

app/helpers/page/conversations_helper.rb
module Page::ConversationsHelper


  def display_sender_name_of_latest_msg(msg)
    unless msg.nil?
      msg.sender.name
    else
      "Not exist msg."
    end
  end

  def display_content_of_latest_msg(msg)
    unless msg.nil?
      msg.content
    else
      "Not exist msg."
    end
  end

end

app/views/page/conversations/index.html.erb
<h1>Listing conversations</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>From</th>
      <th>Latest msg.</th>
      <th>Messages count</th>
      <th>Unread count</th>
      <th>Updated time</th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= display_sender_name_of_latest_msg(conversation.messages.last) %></td>
        <td><%= link_to display_content_of_latest_msg(conversation.messages.last), page_conversation_messages_path(@page, conversation) %></td>
        <td><%= number_with_delimiter(conversation.message_count) %></td>
        <td><%= number_with_delimiter(conversation.unread_count) %></td>
        <td><%= conversation.updated_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>