config/routes.rb
Facepon::Application.routes.draw do

  root 'main#welcome'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', :as => :logout

  resources :pages do
    collection do
      get 'build_pages_collection'
    end

    resources :conversations, :controller => 'page/conversations' do
      collection do
        get 'fetch_from_fb'
      end

      resources :messages, :controller => 'page/messages' do
      end
    end
  end

  

end

app/views/pages/_collection_pages_list.html.erb
<% @fb_pages.each do |fb_page| %>
  <%= content_tag :option, fb_page['name'], {
    :value => fb_page['id'],
    :data => {
        :id => fb_page['id'],
        :category => fb_page['category'],
        :name => fb_page['name']
      }
    } %>
<% end %>

app/views/pages/_form.html.erb
<%= simple_form_for @page do |f| %>
  <%= f.input :name, :as => :hidden %>
  <%= f.input :category, :as => :hidden %>

  <%= link_to "Get pages list from FB", build_pages_collection_pages_path, :remote => true %>
  <%= f.input :page_id, :as => :select, :collection => [] %>

  <%= f.submit %>
<% end %>

<%= content_tag :option, "1" %>

<script>
  $('#page_page_id').change(function(e) {
    var selected_obj = $('#page_page_id option:selected');
    $('#page_name').val( selected_obj.attr('data-name') );
    $('#page_category').val( selected_obj.attr('data-category') );
  });
</script>

app/views/pages/build_pages_collection.js.erb
$('#page_page_id option').remove();
$('#page_page_id').append('<%= escape_javascript(render :partial => "collection_pages_list") %>')

// default
$('#page_name').val('<%= @fb_pages[0]['name'] %>');
$('#page_category').val('<%= @fb_pages[0]['category'] %>');

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<%= link_to 'Add a FB Page', new_page_path, :class => "btn btn-primary" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Pic.</th>
      <th>Name</th>
      <th>Category</th>
      <th>Likes</th>
      <th>Unread message count</th>
      <th>Unseen message count</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= image_tag page.picture %></td>
        <td><%= link_to page.name, page_path(page) %></td>
        <td><%= page.category %></td>
        <td><%= number_with_delimiter(page.likes) %></td>
        <td><%= number_with_delimiter(page.unread_message_count) %></td>
        <td><%= number_with_delimiter(page.unseen_message_count) %></td>
        <td>
          <div class="dropdown">
            <a class="dropdown-toggle btn btn-small" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">Action</a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li><%= link_to "Conversations", page_conversations_path(page) %></li>
              <li><%= link_to "get message from fb", fetch_from_fb_page_conversations_path(page), :remote => true %></li>
              <li><%= link_to "go to facebook page", page.link, :target => :blank %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<script>
  $('.dropdown-toggle').dropdown();
</script>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @page.page_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @page.link %>
</p>

<p>
  <strong>Category:</strong>
  <%= @page.category %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @page.likes %>
</p>

<p>
  <strong>Unread message count:</strong>
  <%= @page.unread_message_count %>
</p>

<p>
  <strong>Unread notif count:</strong>
  <%= @page.unread_notif_count %>
</p>

<p>
  <strong>Unread message count:</strong>
  <%= @page.unread_message_count %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>